// <auto-generated />
namespace XYD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rollbacktooriginconfigtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rollbacktooriginconfigtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202001091223295_roll back to origin config table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
