// <auto-generated />
namespace XYD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class refractorvouchermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refractorvouchermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202002280257442_refractor voucher model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
