// <auto-generated />
namespace XYD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removeworkhistorytalbe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeworkhistorytalbe));
        
        string IMigrationMetadata.Id
        {
            get { return "202001100945011_remove work history talbe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
