// <auto-generated />
namespace XYD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addareatoasset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addareatoasset));
        
        string IMigrationMetadata.Id
        {
            get { return "202003251425540_add area to asset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
