// <auto-generated />
namespace DeptOA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addattmenttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addattmenttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201906060235505_add attment table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
