//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYD.U8Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="U8Service.U8ServiceSoap")]
    public interface U8ServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 key 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStyleNo", ReplyAction="*")]
        XYD.U8Service.UpdateStyleNoResponse UpdateStyleNo(XYD.U8Service.UpdateStyleNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStyleNo", ReplyAction="*")]
        System.Threading.Tasks.Task<XYD.U8Service.UpdateStyleNoResponse> UpdateStyleNoAsync(XYD.U8Service.UpdateStyleNoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 key 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSupplier", ReplyAction="*")]
        XYD.U8Service.UpdateSupplierResponse UpdateSupplier(XYD.U8Service.UpdateSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<XYD.U8Service.UpdateSupplierResponse> UpdateSupplierAsync(XYD.U8Service.UpdateSupplierRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 key 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        XYD.U8Service.UpdateCustomerResponse UpdateCustomer(XYD.U8Service.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<XYD.U8Service.UpdateCustomerResponse> UpdateCustomerAsync(XYD.U8Service.UpdateCustomerRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 key 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Salary", ReplyAction="*")]
        XYD.U8Service.SalaryResponse Salary(XYD.U8Service.SalaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Salary", ReplyAction="*")]
        System.Threading.Tasks.Task<XYD.U8Service.SalaryResponse> SalaryAsync(XYD.U8Service.SalaryRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 TestResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        XYD.U8Service.TestResponse Test(XYD.U8Service.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        System.Threading.Tasks.Task<XYD.U8Service.TestResponse> TestAsync(XYD.U8Service.TestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStyleNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStyleNo", Namespace="http://tempuri.org/", Order=0)]
        public XYD.U8Service.UpdateStyleNoRequestBody Body;
        
        public UpdateStyleNoRequest() {
        }
        
        public UpdateStyleNoRequest(XYD.U8Service.UpdateStyleNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStyleNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string database;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string param;
        
        public UpdateStyleNoRequestBody() {
        }
        
        public UpdateStyleNoRequestBody(string key, string database, string tableName, string param) {
            this.key = key;
            this.database = database;
            this.tableName = tableName;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStyleNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStyleNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public XYD.U8Service.UpdateStyleNoResponseBody Body;
        
        public UpdateStyleNoResponse() {
        }
        
        public UpdateStyleNoResponse(XYD.U8Service.UpdateStyleNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStyleNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateStyleNoResult;
        
        public UpdateStyleNoResponseBody() {
        }
        
        public UpdateStyleNoResponseBody(string UpdateStyleNoResult) {
            this.UpdateStyleNoResult = UpdateStyleNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSupplier", Namespace="http://tempuri.org/", Order=0)]
        public XYD.U8Service.UpdateSupplierRequestBody Body;
        
        public UpdateSupplierRequest() {
        }
        
        public UpdateSupplierRequest(XYD.U8Service.UpdateSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string database;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string param;
        
        public UpdateSupplierRequestBody() {
        }
        
        public UpdateSupplierRequestBody(string key, string database, string tableName, string param) {
            this.key = key;
            this.database = database;
            this.tableName = tableName;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public XYD.U8Service.UpdateSupplierResponseBody Body;
        
        public UpdateSupplierResponse() {
        }
        
        public UpdateSupplierResponse(XYD.U8Service.UpdateSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateSupplierResult;
        
        public UpdateSupplierResponseBody() {
        }
        
        public UpdateSupplierResponseBody(string UpdateSupplierResult) {
            this.UpdateSupplierResult = UpdateSupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomer", Namespace="http://tempuri.org/", Order=0)]
        public XYD.U8Service.UpdateCustomerRequestBody Body;
        
        public UpdateCustomerRequest() {
        }
        
        public UpdateCustomerRequest(XYD.U8Service.UpdateCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string database;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string param;
        
        public UpdateCustomerRequestBody() {
        }
        
        public UpdateCustomerRequestBody(string key, string database, string tableName, string param) {
            this.key = key;
            this.database = database;
            this.tableName = tableName;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public XYD.U8Service.UpdateCustomerResponseBody Body;
        
        public UpdateCustomerResponse() {
        }
        
        public UpdateCustomerResponse(XYD.U8Service.UpdateCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateCustomerResult;
        
        public UpdateCustomerResponseBody() {
        }
        
        public UpdateCustomerResponseBody(string UpdateCustomerResult) {
            this.UpdateCustomerResult = UpdateCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Salary", Namespace="http://tempuri.org/", Order=0)]
        public XYD.U8Service.SalaryRequestBody Body;
        
        public SalaryRequest() {
        }
        
        public SalaryRequest(XYD.U8Service.SalaryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalaryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime BeginDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime EndDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public XYD.U8Service.ArrayOfString wxIdList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public XYD.U8Service.ArrayOfString shIdList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public XYD.U8Service.ArrayOfString specialIdList;
        
        public SalaryRequestBody() {
        }
        
        public SalaryRequestBody(string key, System.DateTime BeginDate, System.DateTime EndDate, XYD.U8Service.ArrayOfString wxIdList, XYD.U8Service.ArrayOfString shIdList, XYD.U8Service.ArrayOfString specialIdList) {
            this.key = key;
            this.BeginDate = BeginDate;
            this.EndDate = EndDate;
            this.wxIdList = wxIdList;
            this.shIdList = shIdList;
            this.specialIdList = specialIdList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalaryResponse", Namespace="http://tempuri.org/", Order=0)]
        public XYD.U8Service.SalaryResponseBody Body;
        
        public SalaryResponse() {
        }
        
        public SalaryResponse(XYD.U8Service.SalaryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalaryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object SalaryResult;
        
        public SalaryResponseBody() {
        }
        
        public SalaryResponseBody(object SalaryResult) {
            this.SalaryResult = SalaryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org/", Order=0)]
        public XYD.U8Service.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(XYD.U8Service.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody {
        
        public TestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org/", Order=0)]
        public XYD.U8Service.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(XYD.U8Service.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface U8ServiceSoapChannel : XYD.U8Service.U8ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class U8ServiceSoapClient : System.ServiceModel.ClientBase<XYD.U8Service.U8ServiceSoap>, XYD.U8Service.U8ServiceSoap {
        
        public U8ServiceSoapClient() {
        }
        
        public U8ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public U8ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public U8ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public U8ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XYD.U8Service.UpdateStyleNoResponse XYD.U8Service.U8ServiceSoap.UpdateStyleNo(XYD.U8Service.UpdateStyleNoRequest request) {
            return base.Channel.UpdateStyleNo(request);
        }
        
        public string UpdateStyleNo(string key, string database, string tableName, string param) {
            XYD.U8Service.UpdateStyleNoRequest inValue = new XYD.U8Service.UpdateStyleNoRequest();
            inValue.Body = new XYD.U8Service.UpdateStyleNoRequestBody();
            inValue.Body.key = key;
            inValue.Body.database = database;
            inValue.Body.tableName = tableName;
            inValue.Body.param = param;
            XYD.U8Service.UpdateStyleNoResponse retVal = ((XYD.U8Service.U8ServiceSoap)(this)).UpdateStyleNo(inValue);
            return retVal.Body.UpdateStyleNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XYD.U8Service.UpdateStyleNoResponse> XYD.U8Service.U8ServiceSoap.UpdateStyleNoAsync(XYD.U8Service.UpdateStyleNoRequest request) {
            return base.Channel.UpdateStyleNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XYD.U8Service.UpdateStyleNoResponse> UpdateStyleNoAsync(string key, string database, string tableName, string param) {
            XYD.U8Service.UpdateStyleNoRequest inValue = new XYD.U8Service.UpdateStyleNoRequest();
            inValue.Body = new XYD.U8Service.UpdateStyleNoRequestBody();
            inValue.Body.key = key;
            inValue.Body.database = database;
            inValue.Body.tableName = tableName;
            inValue.Body.param = param;
            return ((XYD.U8Service.U8ServiceSoap)(this)).UpdateStyleNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XYD.U8Service.UpdateSupplierResponse XYD.U8Service.U8ServiceSoap.UpdateSupplier(XYD.U8Service.UpdateSupplierRequest request) {
            return base.Channel.UpdateSupplier(request);
        }
        
        public string UpdateSupplier(string key, string database, string tableName, string param) {
            XYD.U8Service.UpdateSupplierRequest inValue = new XYD.U8Service.UpdateSupplierRequest();
            inValue.Body = new XYD.U8Service.UpdateSupplierRequestBody();
            inValue.Body.key = key;
            inValue.Body.database = database;
            inValue.Body.tableName = tableName;
            inValue.Body.param = param;
            XYD.U8Service.UpdateSupplierResponse retVal = ((XYD.U8Service.U8ServiceSoap)(this)).UpdateSupplier(inValue);
            return retVal.Body.UpdateSupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XYD.U8Service.UpdateSupplierResponse> XYD.U8Service.U8ServiceSoap.UpdateSupplierAsync(XYD.U8Service.UpdateSupplierRequest request) {
            return base.Channel.UpdateSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<XYD.U8Service.UpdateSupplierResponse> UpdateSupplierAsync(string key, string database, string tableName, string param) {
            XYD.U8Service.UpdateSupplierRequest inValue = new XYD.U8Service.UpdateSupplierRequest();
            inValue.Body = new XYD.U8Service.UpdateSupplierRequestBody();
            inValue.Body.key = key;
            inValue.Body.database = database;
            inValue.Body.tableName = tableName;
            inValue.Body.param = param;
            return ((XYD.U8Service.U8ServiceSoap)(this)).UpdateSupplierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XYD.U8Service.UpdateCustomerResponse XYD.U8Service.U8ServiceSoap.UpdateCustomer(XYD.U8Service.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomer(request);
        }
        
        public string UpdateCustomer(string key, string database, string tableName, string param) {
            XYD.U8Service.UpdateCustomerRequest inValue = new XYD.U8Service.UpdateCustomerRequest();
            inValue.Body = new XYD.U8Service.UpdateCustomerRequestBody();
            inValue.Body.key = key;
            inValue.Body.database = database;
            inValue.Body.tableName = tableName;
            inValue.Body.param = param;
            XYD.U8Service.UpdateCustomerResponse retVal = ((XYD.U8Service.U8ServiceSoap)(this)).UpdateCustomer(inValue);
            return retVal.Body.UpdateCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XYD.U8Service.UpdateCustomerResponse> XYD.U8Service.U8ServiceSoap.UpdateCustomerAsync(XYD.U8Service.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<XYD.U8Service.UpdateCustomerResponse> UpdateCustomerAsync(string key, string database, string tableName, string param) {
            XYD.U8Service.UpdateCustomerRequest inValue = new XYD.U8Service.UpdateCustomerRequest();
            inValue.Body = new XYD.U8Service.UpdateCustomerRequestBody();
            inValue.Body.key = key;
            inValue.Body.database = database;
            inValue.Body.tableName = tableName;
            inValue.Body.param = param;
            return ((XYD.U8Service.U8ServiceSoap)(this)).UpdateCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XYD.U8Service.SalaryResponse XYD.U8Service.U8ServiceSoap.Salary(XYD.U8Service.SalaryRequest request) {
            return base.Channel.Salary(request);
        }
        
        public object Salary(string key, System.DateTime BeginDate, System.DateTime EndDate, XYD.U8Service.ArrayOfString wxIdList, XYD.U8Service.ArrayOfString shIdList, XYD.U8Service.ArrayOfString specialIdList) {
            XYD.U8Service.SalaryRequest inValue = new XYD.U8Service.SalaryRequest();
            inValue.Body = new XYD.U8Service.SalaryRequestBody();
            inValue.Body.key = key;
            inValue.Body.BeginDate = BeginDate;
            inValue.Body.EndDate = EndDate;
            inValue.Body.wxIdList = wxIdList;
            inValue.Body.shIdList = shIdList;
            inValue.Body.specialIdList = specialIdList;
            XYD.U8Service.SalaryResponse retVal = ((XYD.U8Service.U8ServiceSoap)(this)).Salary(inValue);
            return retVal.Body.SalaryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XYD.U8Service.SalaryResponse> XYD.U8Service.U8ServiceSoap.SalaryAsync(XYD.U8Service.SalaryRequest request) {
            return base.Channel.SalaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<XYD.U8Service.SalaryResponse> SalaryAsync(string key, System.DateTime BeginDate, System.DateTime EndDate, XYD.U8Service.ArrayOfString wxIdList, XYD.U8Service.ArrayOfString shIdList, XYD.U8Service.ArrayOfString specialIdList) {
            XYD.U8Service.SalaryRequest inValue = new XYD.U8Service.SalaryRequest();
            inValue.Body = new XYD.U8Service.SalaryRequestBody();
            inValue.Body.key = key;
            inValue.Body.BeginDate = BeginDate;
            inValue.Body.EndDate = EndDate;
            inValue.Body.wxIdList = wxIdList;
            inValue.Body.shIdList = shIdList;
            inValue.Body.specialIdList = specialIdList;
            return ((XYD.U8Service.U8ServiceSoap)(this)).SalaryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XYD.U8Service.TestResponse XYD.U8Service.U8ServiceSoap.Test(XYD.U8Service.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public string Test() {
            XYD.U8Service.TestRequest inValue = new XYD.U8Service.TestRequest();
            inValue.Body = new XYD.U8Service.TestRequestBody();
            XYD.U8Service.TestResponse retVal = ((XYD.U8Service.U8ServiceSoap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XYD.U8Service.TestResponse> XYD.U8Service.U8ServiceSoap.TestAsync(XYD.U8Service.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<XYD.U8Service.TestResponse> TestAsync() {
            XYD.U8Service.TestRequest inValue = new XYD.U8Service.TestRequest();
            inValue.Body = new XYD.U8Service.TestRequestBody();
            return ((XYD.U8Service.U8ServiceSoap)(this)).TestAsync(inValue);
        }
    }
}
